spring.application.name=core-engine

# PostgreSQL Temiz Baglanti Ayarlari (Portu 5432 ve sifreyi root yaptik)
spring.datasource.url=jdbc:postgresql://localhost:5432/safetransact
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate/JPA Ayarlari (Java koduna gore tablolari otomatik olusturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect